### ISSUE TITLE
Protoype: Citation Context Report

### ISSUE THREAD

**Issue by Bubblbu** [Bubblbu/metrics-in-context#28]
The folder for all things related to this issue is `hackathon/1_report`

I am personally planning to spend most of my working/coding time on this issue as it most intimately relates to the ongoing work for Metrics in Context. I am still obviously excited about all contributions and feedback.

**This issue might be a good fit for:**

- Developers who want to dive into Frictionless and/or livemark
- Anyone who is interested in the broader project Metrics in Context
- Scientometricians who are into the nitty-gritty details of methodology and data
- also, any bored scientometricians very welcome to come and chat 🤷

**Tasks:**

- [x] #33
- [x] MVP: Livemark & Tabular Data Packages
- [x] Load citation data & metadata schema
- [x] Include citation index profiles
- [ ] Livemark report that accesses citation data
